from fastapi import APIRouter, HTTPException, status, Request
from src.models.query_model import QueryRequest, QueryResponse, ImpactScoreModel
from src.services.llm_service import get_legal_response
from src.services.parser import parse_llm_output
from src.services.language_service import detect_language, get_language_name
from src.services.feedback_processor import FeedbackProcessor, ScoreFeedback, ScoreFeedbackResponse

# ✅ NEW IMPORT
from src.services.simulator import simulate_action

import logging
import uuid
import time

logger = logging.getLogger(__name__)
router = APIRouter()


@router.post("/query", response_model=QueryResponse, status_code=200)
def handle_query(req: QueryRequest, request: Request) -> QueryResponse:

    request_id = str(uuid.uuid4())
    start_time = time.time()

    try:
        logger.info(f"[{request_id}] New chatbot query received: {req.query[:80]}...")

        # ===============================
        # ✅ SIMULATOR MODE DETECTION
        # ===============================

        text = req.query.lower()

        SIMULATE_WORDS = [
            "can i",
            "what happens",
            "is it legal",
            "simulate",
            "if i",
            "suppose i",
            "erase",
            "delete",
            "record",
            "post",
            "terminate",
            "hack",
            "threat",
            "fraud",
            "illegal",
            "penalty",
            "punishment"
        ]

        if any(word in text for word in SIMULATE_WORDS):

            logger.info(f"[{request_id}] Simulator mode detected")

            sim_result = simulate_action(req.query)

            return QueryResponse(
                summary=str(sim_result),
                laws=[],
                suggestions=["Generated by Legal Consequence Simulator"],
                request_id=request_id,
                language="en",
                impact_score=ImpactScoreModel(
                    overall_score=8,
                    financial_risk_score=8,
                    legal_exposure_score=9,
                    long_term_impact_score=7,
                    rights_lost_score=6,
                    risk_level="High Risk",
                    breakdown={"note": "Generated by simulator"},
                    key_factors=[],
                    mitigating_factors=[],
                    recommendation="Avoid risky legal action and consult a legal professional"
                )
            )

        # ===============================
        # NORMAL CHATBOT PIPELINE
        # ===============================

        # Detect language
        if req.language:
            language = req.language.lower()
            logger.info(f"[{request_id}] Language: {language} (provided)")
        else:
            language = detect_language(req.query)
            logger.info(f"[{request_id}] Language auto-detected: {language}")

        # Call LLM
        logger.debug(f"[{request_id}] Calling LLM service...")
        raw_output = get_legal_response(req.query, language=language)

        # Parse response
        logger.debug(f"[{request_id}] Parsing LLM response...")
        parsed = parse_llm_output(raw_output)

        parsed["request_id"] = request_id
        parsed["language"] = language

        # Default impact score
        if "impact_score" not in parsed or parsed["impact_score"] is None:
            parsed["impact_score"] = ImpactScoreModel(
                overall_score=0,
                financial_risk_score=0,
                legal_exposure_score=0,
                long_term_impact_score=0,
                rights_lost_score=0,
                risk_level="Assessment not performed",
                breakdown={"note": "Chatbot response"},
                key_factors=[],
                mitigating_factors=[],
                recommendation="Consult legal professional"
            )

        elapsed = time.time() - start_time
        logger.info(f"[{request_id}] Query processed successfully in {elapsed:.2f}s")

        response = QueryResponse(**parsed)
        return response

    except Exception as e:

        elapsed = time.time() - start_time
        logger.exception(f"[{request_id}] Error after {elapsed:.2f}s: {str(e)}")

        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="An unexpected error occurred while processing your query."
        )


# ===============================
# FEEDBACK SYSTEM (unchanged)
# ===============================

feedback_processor = FeedbackProcessor()


@router.post("/feedback/score", response_model=ScoreFeedbackResponse, status_code=200)
def submit_score_feedback(feedback: ScoreFeedback) -> ScoreFeedbackResponse:

    try:

        logger.info(
            f"Received score feedback for request {feedback.request_id}: "
            f"rating={feedback.user_rating}/5, type={feedback.feedback_type}"
        )

        result = feedback_processor.submit_feedback(feedback)

        return ScoreFeedbackResponse(
            status=result["status"],
            message=result["message"]
        )

    except Exception as e:

        logger.error(f"Failed to process feedback: {str(e)}", exc_info=True)

        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Failed to submit feedback."
        )


@router.get("/feedback/analysis", status_code=200)
def get_feedback_analysis():

    try:

        logger.info("Retrieving feedback analysis...")
        analysis = feedback_processor.get_analysis()

        return analysis

    except Exception as e:

        logger.error(f"Failed to retrieve feedback analysis: {str(e)}", exc_info=True)

        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Failed to retrieve feedback analysis."
        )